jokes/urls.py
from django.urls import path

from jokes.views import CategoryListView
from jokes.views import RatingView

app_name = 'jokes'

urlpatterns = [
    path('categories/<str:category>', CategoryListView.as_view(), name='categories'),
    path('rating', RatingView.as_view(), name='rating'),
]

users/urls.py
from django.urls import path

from users.views import UserListView

app_name = 'users'

urlpatterns = [
    path('<str:user>', UserListView.as_view(), name='details'),
]

jokes/models.py
from django.contrib.auth.models import User
from django.db import models

from multiselectfield import MultiSelectField

from core.models import AuditTrailAbstractModel
from core.models import IsActiveAbstractModel


class Joke(AuditTrailAbstractModel, IsActiveAbstractModel):
    # Reference
    #   Every Joke Falls in One of 11 Categories, Says Founding Editor of The Onion
    #   https://bigthink.com/stephen-johnson/every-joke-falls-in-one-of-these-11-categories-according-to-the-founder-of-the-onion
    CATEGORY_CHOICES = (
        ('IR', 'Irony'),
        ('CH', 'Character'),
        ('RE', 'Reference'),
        ('SH', 'Shock'),
        ('PA', 'Parody'),
        ('HY', 'Hyperbole'),
        ('WO', 'Wordplay'),
        ('AN', 'Analogy'),
        ('MA', 'Madcap'),
        ('ME', 'Meta-humor'),
        ('MI', 'Misplaced-focus'),
    )

    sender = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Sender')
    category = MultiSelectField(choices=CATEGORY_CHOICES, verbose_name='Category')
    title = models.CharField(max_length=128, verbose_name='Title')
    joke = models.TextField(verbose_name='Joke')

    class Meta:
        db_table = 'joke'
        verbose_name = 'Joke'
        verbose_name_plural = 'Jokes'
        ordering = ('-created_date',)

    def __str__(self):
        return self.title


class JokeRating(AuditTrailAbstractModel):
    critic = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Critic')
    joke = models.ForeignKey(Joke, on_delete=models.CASCADE, verbose_name='Joke')
    rating = models.NullBooleanField(verbose_name='Rating')

    class Meta:
        db_table = 'joke_rating'
        verbose_name = 'Joke Rating'
        verbose_name_plural = 'Joke Ratings'
        ordering = ('-created_date',)

    def __str__(self):
        return '{} - {} - {}'.format(self.critic, str(self.joke), str(self.rating))


class JokeRatingCount(AuditTrailAbstractModel):
    joke = models.ForeignKey(Joke, on_delete=models.CASCADE, verbose_name='Joke')
    thumbs_up = models.IntegerField(default=0)
    thumbs_down = models.IntegerField(default=0)

    class Meta:
        db_table = 'joke_rating_count'
        verbose_name = 'Joke Rating Count'
        verbose_name_plural = 'Joke Rating Count'
        ordering = ('-created_date',)

    def __str__(self):
        return '{} - {} - {}'.format(str(self.joke), str(self.thumbs_up), str(self.thumbs_down))

jokes/views.py
from django.views.generic import View
from django.http.response import JsonResponse

from core.views import JokeListViewWithCategory
from jokes.models import Joke
from jokes.models import JokeRating
from jokes.models import JokeRatingCount
from users.models import UserJokeability


class JokeListView(JokeListViewWithCategory):
    pass


class CategoryListView(JokeListViewWithCategory):
    template_name = 'jokes/category_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['category'] = self.kwargs.get('category').capitalize()
        return context

    def get_queryset(self):
        category = self.kwargs.get('category')
        category_choice = ''

        # Get category value based on category text URL slug received
        for cat in Joke.CATEGORY_CHOICES:
            value = cat[0]
            text = cat[1].lower()
            if text == category:
                category_choice = value
                break

        return Joke.objects.filter(category__contains=category_choice).order_by('-created_date')


class RatingView(View):

    def get(self, *args, **kwargs):
        user = self.request.user
        pk = self.request.GET.get('pk', None)

        # Get last rating
        try:
            joke_rating = JokeRating.objects.filter(joke_id=pk, critic=user).first()
            last_rating = joke_rating.rating
        except (AttributeError, TypeError):
            last_rating = None

        # Get last count
        rating_count = JokeRatingCount.objects.filter(joke_id=pk).first()

        try:
            # Get last joke rating count
            data = {'up': rating_count.thumbs_up, 'down': rating_count.thumbs_down, }
        except AttributeError:
            data = {'up': 0, 'down': 0, }
        finally:
            data['rating'] = last_rating
            return JsonResponse(data)

    def post(self, *args, **kwargs):
        user = self.request.user
        pk = self.request.POST.get('pk', None)
        rating = self.request.POST.get('rating', None)

        # Get previous rating and count
        prev_rating = JokeRating.objects.filter(joke_id=pk, critic=user).first()
        prev_count = JokeRatingCount.objects.filter(joke_id=pk).first()

        # Prepare new count
        try:
            new_count = JokeRatingCount(
                joke_id=pk, thumbs_up=prev_count.thumbs_up, thumbs_down=prev_count.thumbs_down
            )
        except AttributeError:
            new_count = JokeRatingCount(joke_id=pk)

        #
        #   Update rating
        #
        if rating == 'true':
            rating = True
            new_count.thumbs_up += 1
        elif rating == 'false':
            rating = False
            new_count.thumbs_down += 1
        else:
            # If new rating is 'None', base the deduction on previous rating
            rating = None
            if prev_rating.rating:
                new_count.thumbs_up -= 1
            else:
                new_count.thumbs_down -= 1

        #
        #   If rating is switched, reduce previous position count
        #
        try:
            if rating and prev_rating.rating is False:
                new_count.thumbs_down = abs(new_count.thumbs_down - 1)
            elif rating is False and prev_rating:
                new_count.thumbs_up = abs(new_count.thumbs_up - 1)
        except AttributeError:
            pass

        #
        #   Update user jokeability rating
        #
        prev_jokeability = UserJokeability.objects.filter(joker_id=new_count.joke.sender_id).first()
        new_jokeability = UserJokeability(joker_id=new_count.joke.sender_id)
        try:
            # Try to get new jokability values based on previous and current counts
            new_jokeability.thumbs_up = abs(prev_jokeability.thumbs_up + (
                    new_count.thumbs_up - prev_count.thumbs_up))
            new_jokeability.thumbs_down = abs(prev_jokeability.thumbs_down + (
                    new_count.thumbs_down - prev_count.thumbs_down))
        except AttributeError:
            try:
                # Else, get new jokabiltiy values based on previous jokability values and new count
                new_jokeability.thumbs_up = prev_jokeability.thumbs_up + new_count.thumbs_up
                new_jokeability.thumbs_down = prev_jokeability.thumbs_down + new_count.thumbs_down
            except AttributeError:
                # Else, new jokability will be the values of the new count
                new_jokeability.thumbs_up = new_count.thumbs_up
                new_jokeability.thumbs_down = new_count.thumbs_down
        finally:
            # Now, compute jokability percent
            try:
                new_jokeability.jokeability = round(
                        new_jokeability.thumbs_up / (new_jokeability.thumbs_up + new_jokeability.thumbs_down), 4)
            except ZeroDivisionError:
                new_jokeability.jokeability = 0.0

        # Save new rating
        new_rating = JokeRating(critic=user, joke_id=pk, rating=rating)
        new_rating.save()

        # Save new count
        new_count.save()

        # Save new jokeability
        new_jokeability.save()

        return JsonResponse(data={'up': new_count.thumbs_up, 'down': new_count.thumbs_down, })

templates/jokes/category_list.html
{% extends 'list_base.html' %}

{% load static %}

{% block title %}Category {{ category }} :: Jokeability{% endblock title %}

{% block page_title %}Category: <b>{{ category }}</b>{% endblock page_title %}

{% block content %}
    {% include 'jokes/list_content.html' %}
{% endblock content %}

templates/jokes/joke_list.html
{% extends 'list_base.html' %}

{% load static %}

{% block title %}All: Jokeability{% endblock title %}

{% block page_title %}<b>All Jokes</b>{% endblock page_title %}

{% block content %}
    {% include 'jokes/list_content.html' %}
{% endblock content %}

templates/jokes/list_content.html
{% csrf_token %}

{% for joke in page_obj %}
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">
                {{ joke.title }}
                <small>{{ joke.category }}</small>
            </h3>
        </div>
        <div class="box-body">
            <p>{{ joke.joke|linebreaks }}</p>
            <br>
            <p class="rating">
                {% if user.is_authenticated %}
                    <button class="btn btn-default thumbs-up" title="Thumbs Up"><span class="count">#</span> <i class="fa fa-thumbs-o-up"></i></button>
                    <button class="btn btn-default thumbs-down" title="Thumbs Down"><span class="count">#</span> <i class="fa fa-thumbs-o-down"></i></button>
                {% else %}
                    <button class="btn btn-default thumbs-up" title="Thumbs Up" disabled="disabled"><span class="count">#</span> <i class="fa fa-thumbs-o-up"></i></button>
                    <button class="btn btn-default thumbs-down" title="Thumbs Down" disabled="disabled"><span class="count">#</span> <i class="fa fa-thumbs-o-down"></i></button>
                {% endif %}
                <input type="hidden" value="{{ joke.pk }}">
            </p>
        </div>
        <div class="box-footer">
            <small>Joke by <a href="{% url 'users:details' joke.sender.username %}"><b>{{ joke.sender.username }}</b></a>. Submitted{{ joke.modified_date }}.</small>
        </div>
    </div>
{% endfor %}

<div class="text-center">

    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li><a href="?page=1"><i class="fa fa-angle-double-left"></i></a></li>
            <li><a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left"></i></a></li>
        {% endif %}

        <li class="disabled"><a href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>

        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right"></i></a></li>
            <li><a href="?page={{ page_obj.paginator.num_pages }}"><i class="fa fa-angle-double-right"></i></a></li>
        {% endif %}
    </ul>
</div>